Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/AbcSize:
  Max: 40

Style/Documentation:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/AlignHash:
  Severity: fatal
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/DotPosition:
  EnforcedStyle: leading

Style/DoubleNegation:
  Enabled: false

Style/SpaceAroundOperators:
  # When true, allows most uses of extra spacing if the intent is to align
  # with an operator on the previous or next line, not counting empty lines
  # or comment lines.
  AllowForAlignment: true
