sudo: false

language: ruby
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - jruby-19mode
  - rbx

# Ensure we don't build for *every* commit (doesn't apply to PR builds)
branches:
  only:
  - master

env:
  global:
    - USE_SIMPLECOV=true

before_install:
  - gem update bundler
